CXX = cl.exe
CFLAGS = /nologo /O2 /EHsc /I. /D _WIN64 /D _CRT_SECURE_NO_DEPRECATE

liball: all
# remove temp files
    -erase /Q *.obj *.lib *.exp

all: lib

linear.obj: linear.cpp linear.h
	$(CXX) $(CFLAGS) -c linear.cpp

tron.obj: tron.cpp tron.h
	$(CXX) $(CFLAGS) -c tron.cpp

lib: linear.cpp linear.h linear.def tron.obj
	$(CXX) $(CFLAGS) -LD linear.cpp tron.obj blas\*.c -Feliblinear -link -DEF:linear.def

clean:
	 -erase /Q *.obj *.dll *.lib *.exp

